// Fonte dos tokens. scripts/build.mjs gera dist/tokens.css a partir daqui.
// Três camadas (ADR 0003): apps e componentes usam só semânticos e de componente.

export const primitives = {
  'color-neutral-0': '#ffffff',
  'color-neutral-100': '#eef0f4',
  'color-neutral-300': '#c3c8d2',
  'color-neutral-600': '#4d5565',
  'color-neutral-900': '#161a22',
  'color-neutral-950': '#0c0e13',
  'color-blue-300': '#93c5fd',
  'color-blue-700': '#1d4ed8',
  // Cenário de sakura da home.
  'color-sky-200': '#d6e6f5',
  'color-pink-50': '#fdeef2',
  'color-pink-200': '#f9c2d0',
  'color-pink-300': '#f29bb5',
  'color-pink-500': '#d9487a',
  'color-brown-700': '#6b4a3f',
  'color-indigo-950': '#0f1535',
  'color-indigo-600': '#45488a',
  'color-cream-100': '#f6efd9',
  'color-cloud-light': '#ffffffb3',
  'color-cloud-dark': '#a9aee04d',
  // Sol do hinomaru, no seletor de tema.
  'color-red-600': '#bc002d',
  'ratio-0': '0',
  'ratio-1': '1',
  'space-1': '0.25rem',
  'space-2': '0.5rem',
  'space-4': '1rem',
  'space-6': '1.5rem',
  'space-8': '2rem',
  'border-width-medium': '2px',
  'border-width-thick': '3px',
  'size-11': '2.75rem',
  'duration-200': '200ms',
  'duration-500': '500ms',
  'duration-4000': '4s',
  'duration-12000': '12s',
  'ease-out': 'cubic-bezier(0.2, 0, 0, 1)',
  'radius-12': '0.75rem',
  'radius-pill': '999px',
  'font-sans': "system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
  'font-size-100': '0.875rem',
  'font-size-200': '1rem',
  'font-size-300': '1.25rem',
  'font-size-500': '1.75rem',
  'font-weight-strong': '600',
  'line-height-body': '1.5',
};

/** Mudam de valor conforme o tema. As duas listas têm as mesmas chaves. */
export const semantic = {
  light: {
    'color-surface': 'var(--color-neutral-0)',
    'color-surface-muted': 'var(--color-neutral-100)',
    'color-text': 'var(--color-neutral-900)',
    'color-text-muted': 'var(--color-neutral-600)',
    'color-border': 'var(--color-neutral-300)',
    'color-accent': 'var(--color-blue-700)',
    'color-on-accent': 'var(--color-neutral-0)',
    'color-focus-ring': 'var(--color-blue-700)',
    'color-scene-sky-top': 'var(--color-sky-200)',
    'color-scene-sky-bottom': 'var(--color-pink-50)',
    'color-scene-sun': 'var(--color-neutral-0)',
    'color-scene-moon': 'var(--color-cream-100)',
    'color-scene-cloud': 'var(--color-cloud-light)',
    // 1 de dia, 0 à noite: a home usa para pôr o sol e erguer a lua.
    'scene-daylight': 'var(--ratio-1)',
    'color-scene-branch': 'var(--color-brown-700)',
    'color-scene-blossom': 'var(--color-pink-200)',
    'color-scene-blossom-core': 'var(--color-pink-500)',
    'color-scene-petal': 'var(--color-pink-300)',
    // Contorno da letra sobre o cenário: o tom do alto do céu.
    'color-scene-outline': 'var(--color-sky-200)',
    'color-celestial': 'var(--color-red-600)',
  },
  dark: {
    'color-surface': 'var(--color-neutral-950)',
    'color-surface-muted': 'var(--color-neutral-900)',
    'color-text': 'var(--color-neutral-100)',
    'color-text-muted': 'var(--color-neutral-300)',
    'color-border': 'var(--color-neutral-600)',
    'color-accent': 'var(--color-blue-300)',
    'color-on-accent': 'var(--color-neutral-950)',
    'color-focus-ring': 'var(--color-blue-300)',
    'color-scene-sky-top': 'var(--color-indigo-950)',
    'color-scene-sky-bottom': 'var(--color-indigo-600)',
    'color-scene-sun': 'var(--color-neutral-0)',
    'color-scene-moon': 'var(--color-cream-100)',
    'color-scene-cloud': 'var(--color-cloud-dark)',
    'scene-daylight': 'var(--ratio-0)',
    'color-scene-branch': 'var(--color-indigo-600)',
    'color-scene-blossom': 'var(--color-pink-50)',
    'color-scene-blossom-core': 'var(--color-pink-200)',
    'color-scene-petal': 'var(--color-pink-50)',
    'color-scene-outline': 'var(--color-indigo-950)',
    'color-celestial': 'var(--color-cream-100)',
  },
};

/** Não mudam com o tema, mas apps os usam no lugar dos primitivos. */
export const semanticStatic = {
  'space-inline-sm': 'var(--space-2)',
  'space-inline-md': 'var(--space-4)',
  'space-inline-lg': 'var(--space-8)',
  'space-block-xs': 'var(--space-1)',
  'space-block-sm': 'var(--space-2)',
  'space-block-md': 'var(--space-4)',
  'space-block-lg': 'var(--space-6)',
  'focus-ring-width': 'var(--border-width-thick)',
  'border-width-control': 'var(--border-width-medium)',
  'text-outline-width': 'var(--border-width-medium)',
  'size-control': 'var(--size-11)',
  'focus-ring-offset': 'var(--space-1)',
  'motion-duration-md': 'var(--duration-200)',
  'motion-ease-out': 'var(--ease-out)',
  'motion-duration-theme': 'var(--duration-500)',
  'motion-duration-sway': 'var(--duration-4000)',
  'motion-duration-drift': 'var(--duration-12000)',
  'font-body': 'var(--font-sans)',
  'text-size-sm': 'var(--font-size-100)',
  'text-size-md': 'var(--font-size-200)',
  'text-size-lg': 'var(--font-size-300)',
  'text-size-title': 'var(--font-size-500)',
  'text-weight-strong': 'var(--font-weight-strong)',
  'text-line-height': 'var(--line-height-body)',
  'radius-md': 'var(--radius-12)',
  'radius-full': 'var(--radius-pill)',
};

export const component = {
  'ds-badge-bg': 'var(--color-accent)',
  'ds-badge-text': 'var(--color-on-accent)',
  'ds-badge-padding-block': 'var(--space-block-xs)',
  'ds-badge-padding-inline': 'var(--space-inline-sm)',
  'ds-badge-radius': 'var(--radius-full)',
  'ds-badge-font-size': 'var(--text-size-sm)',
  'ds-theme-toggle-bg': 'var(--color-surface)',
  'ds-theme-toggle-border': 'var(--color-text-muted)',
  'ds-theme-toggle-icon': 'var(--color-celestial)',
  'ds-theme-toggle-size': 'var(--size-control)',
  'ds-theme-toggle-border-width': 'var(--border-width-control)',
  'ds-theme-toggle-radius': 'var(--radius-full)',
  'ds-theme-toggle-duration': 'var(--motion-duration-theme)',
};
